### PR TITLE
install extra dependencies

### PR DESCRIPTION
**Pull request by thijstriemstra**
Adding pytz (for improved timezone config) and Babel (for localization).

### CODE REVIEW

**Comment by techtonik** [comment]
Are you sure that Twisted users should avoid reading English?

**Comment by thijstriemstra** [comment]
True, removed the `Babel` dependency. Please review.

**Comment by techtonik** [comment]
LGTM.

**Comment by thijstriemstra** [comment]
Can anyone with write permissions merge this? @glyph?

**Comment by glyph** [comment]
Is this just an optional dependency of Trac, and timezone formatting will magically get better if we install it?  Unfortunately testing stuff like this is mind-blowingly difficult, so it's good to know ahead of time what should happen :-\

**Comment by techtonik** [comment]
I think that the effect is that:
1. timezone configuration will become available
2. timezones will be correct
And this setting should be in user profile.

But I am not sure if that's an issue with latest Trac releases. It may reuse system settings somehow.

**Pull request closed without merging**
